---
  #install grails
  - name: "Install sdkman for Grails installation"
    command: "curl -s get.sdkman.io | bash"
    become: yes

  - name: "Refresh sdkman"
    command: "source "$HOME/.sdkman/bin/sdkman-init.sh""
    become: yes

  - name: "Install grails version 2.4.5"
    command: "sdk install grails 2.4.5"
    become: yes

  - name: "Install Tomcat and Ant"
    apt: pkg={{ item }} state=installed
    with_items:
        - tomcat7
        - tomcat7-admin
        - ant
    become: yes

   #increase memory
  - name: "Increase memory for tomcat"
    copy: src="files/setenv.sh" dest="/usr/share/tomcat7" owner=ubuntu mode=0755
    become: yes

  - name: "Install apollo"
    git: repo=https://github.com/GMOD/Apollo.git dest=/mnt/gvl/apps/apollo version=2.0.2
   #install apollo - git clone. This should be versioned
   #73  cd /mnt/gvl/apps/
   #74  git clone https://github.com/GMOD/Apollo.git Apollo
   #75  cd Apollo/

  - name: "Copy postgres config files"
    copy: src="files/postgres-apollo-config.groovy" dest="/mnt/gvl/apps/apollo/" owner=ubuntu mode=0600

   #copy apollo config from files
   #77  nano sample-postgres-apollo-config.groovy
   #78  ./apollo run-local
   #79  ./apollo run-local --stacktrace

  - name: "Create the database postgres user"
    command: sudo su postgres -c "createuser -RDIElPS database_user"
    args:
      chdir: /mnt/gvl/apps/

  - name: "Create database"
    command: sudo su postgres -c "createdb -E UTF-8 -O database_user apollo-production"
    args:
      chdir: /mnt/gvl/apps/

   #95  sudo su postgres -c "createuser -RDIElPS database_user"
   #96  cd /mnt/gvl/apps/
   #101  sudo su postgres -c "createdb -E UTF-8 -O database_user apollo-production"

  - name: "Deploy apollo"
    command: "./apollo deploy"
    args:
      chdir: /mnt/gvl/apps/

   #107  ./apollo deploy

  #copy files for tomcat (server.xml)
  #make sure it looks in the right place for the war files!
  122  sudo nano server.xml
  123  service tomcat7 restart

  #remove the default tomcat war file
  124  cd /var/lib/tomcat7/webapps/
  125  ls
  126  cd ROOT/
  127  ls
  128  cd ..

  #copy apollo into folder
  129  cp /mnt/gvl/apps/Apollo/target/apollo-2.0.3-SNAPSHOT.war .
  138  mv apollo-2.0.3-SNAPSHOT.war apollo.war
  130  service tomcat7 restart
  131  cd ROOT/

  #check what I changed here
  135  sudo nano context.xml

  142  cd tomcat7/webapps/
  144  sudo nano /var/lib/tomcat7/conf/server.xml

  #add file to nginx folder to get tomcat and nginx to talk
  226  cd /etc/nginx/sites-enabled/
  251  sudo nano apollo.locations
  252  service nginx restart
